// src/games/dto/get-game-dto.ts

import { System, StockStatus } from '@prisma/client'; // Assuming enums are auto-generated by Prisma

export class GetGameDto {
  id?: string;
  productName?: string;
  displayName?: string;
  aboutThisGame?: string;
  cardDescription?: string;
  system?: System;
  languages?: string[];        // Optional filter by language array
  releaseDate?: Date;          // Optional filter by release date
  regularPrice?: number;
  sellingPrice?: number;
  stock?: number;
  SKU?: string;
  stockStatus?: StockStatus;
  minimumOS?: string;
  minimumCPU?: string;
  minimumRAM?: string;
  minimumGPU?: string;
  minimumStorage?: string;
  recommendedOS?: string;
  recommendedCPU?: string;
  recommendedRAM?: string;
  recommendedGPU?: string;
  recommendedStorage?: string;
  coverImage?: string;
  screenshots?: string[];
  video?: string;
  cardImage?: string;
  latestImage?: string;
  addToLatestGames?: boolean;
  addToCarousel?: boolean;
  displayInLatesGames?: boolean;
  published?: boolean;
  brandId?: string;
  platformId?: string;

  page?: number;
  limit?: number;

  // Relationships
  categoryIds?: string[];     // Array of category IDs to filter by categories
  tagIds?: string[];          // Array of tag IDs to filter by tags
  reviewIds?: string[];       // Array of review IDs to filter by reviews
}
